#!/bin/sh
# Package Maintainers
MAINTAINERS=("TigerClips1 <spongebob1966@proton.me>")

# Package information
NAME="gcc"
VERSION="13.2.0"
EPOCH=1
DESC="The GNU Compiler Collection, including C, C++"
GRPS=("devel")
URL="https://gcc.gnu.org/"
LICENSES=("GPL" "LGPL")
DEPENDS=("mpc" "flex" "isl" "libgcc")
OPT_DEPENDS=()
MK_DEPENDS=("dejagnu")
PROVIDES=("gcc")
CONFLICTS=()
REPLACES=()

# Source information
SRC=("https://mirror.fileplanet.com/lfs/pub/lfs/lfs-packages/12.1/gcc-${VERSION}/gcc-${VERSION}.tar.xz")

SUM_TYPE="md5sum"
SUM=("e0e48554cc6e4f261d55ddee9ab69075")

# Prepare script
function prepare() {
    cd "${WORKDIR}/${NAME}-${VERSION}"

    case $(uname -m) in
    x86_64)
        sed -e '/m64=/s/lib64/lib/' \
            -i.orig gcc/config/i386/t-linux64
    ;;
    esac

    mkdir -v build
    cd       build

    ../configure --prefix=/usr            \
                LD=ld                    \
                --enable-languages=c,c++ \
                --enable-default-pie     \
                --enable-default-ssp     \
                --disable-multilib       \
                --disable-bootstrap      \
                --disable-fixincludes    \
                --with-system-zlib

    return 0
}

# Build script
function build() {
    cd "${WORKDIR}/${NAME}-${VERSION}/build"

    make -j8

    ulimit -s 32768
    make -j8 -k check
    
    ../contrib/test_summary
    echo "Please check if all tests passed."
    echo "80 unexpected failures are expected."
    read -s -n 1 -p "Press any key to continue . . ."

    return 0
}

# Post build script
function postbuild() {
    cd "${WORKDIR}/${NAME}-${VERSION}/build"

    DESTDIR="${BUILD_DATA_ROOT}" make install
    ln -svr /usr/bin/cpp /usr/lib
    ln -sv gcc.1 /usr/share/man/man1/cc.1
    ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/13.2.0/liblto_plugin.so \
        /usr/lib/bfd-plugins/
    echo 'int main(){}' > dummy.c
    cc dummy.c -v -Wl,--verbose &> dummy.log
    readelf -l a.out | grep ': /lib'
    grep -E -o '/usr/lib.*/S?crt[1in].*succeeded' dummy.log
    grep -B4 '^ /usr/include' dummy.log
    grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
    grep "/lib.*/libc.so.6 " dummy.log
    grep found dummy.log
    rm -v dummy.c a.out dummy.log
    mkdir -pv /usr/share/gdb/auto-load/usr/lib
    mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
    return 0
}

printf ("DONE")