#!/bin/sh
# Package Maintainers
MAINTAINERS=("TigerClips1 <spongebob1966@proton.me>")

# Package information
NAME="bash"
VERSION="5.2.21"
EPOCH=0
DESC="he Bash package contains the Bourne-Again Shell."
GRPS=("base")
URL="https://gcc.gnu.org/"
LICENSES=("GPL3 or later")
DEPENDS=("glibc", "ncurses", "readline")
OPT_DEPENDS=()
PROVIDES=("bash")
CONFLICTS=()
REPLACES=()

# Source information
SRC=("https://mirror.fileplanet.com/lfs/pub/lfs/lfs-packages/12.1/bash-${VERSION}bash-${VERSION}.tar.gz"
     "https://mirror.fileplanet.com/lfs/pub/lfs/lfs-packages/12.1/bash-5.2.21-upstream_fixes-1.patch")

SUM_TYPE="md5sum"
SUM=("ad5b38410e3bf0e9bcc20e2765f5e3f9"
     "2d1691a629c558e894dbb78ee6bf34ef")

function prepare() {
    cd "${WORKDIR}/${NAME}-${VERSION}"
    patch -Np1 -i ../bash-5.2.21-upstream_fixes-1.patch
    ./configure --prefix=/usr             \
            --without-bash-malloc     \
            --with-installed-readline \
            --docdir=/usr/share/doc/bash-5.2.21
    return 0
}

function build()
{
    make -j8
    return 0
}

function check()
{
    su -s /usr/bin/expect $USER << "EOF"
    set timeout -1
    spawn make tests
    expect eof
    lassign [wait] _ _ _ value
    exit $value
    EOF

    make install
    exec /usr/bin/bash --login
    return 0
}

printf "\nDone\n"

return 0
