#!/bin/sh
# Package Maintainers
MAINTAINERS=("TigerClips1 <spongebob1966@proton.me>")

# Package information
NAME="linux"
VERSION="5.15-rc7"
EPOCH=1
DESC="The linux kernel and the headers and modules"
GRPS=("core")
URL="https://github.com/TigerClips1"
LICENSES=("GPL 2.0 and 3")
DEPENDS=("coreutils", "flex","gcc", "g++", "libgcc", "kmod")
OPT_DEPENDS=("linux-firmware", "wireless-regdb")
MK_DEPENDS=("texlive-latexextra", "python-yaml", "python-sphinx", "xz", "imagemagick", "graphviz", "tar", "perl", "pahole", "libelf", "gettext", "cpio", "bc")
PROVIDES=("linux")
CONFLICTS=()
REPLACES=()

# Source information
SRC=("https://mirror.fileplanet.com/lfs/pub/lfs/lfs-packages/12.1/gcc-${VERSION}/gcc-${VERSION}.tar.xz")

SUM_TYPE="md5sum"
SUM=("e0e48554cc6e4f261d55ddee9ab69075")

# Prepare script
function prepare() {
    cd "${WORKDIR}/${NAME}-${VERSION}"
    make mrproper
    mv config .config
    return 0
}

# Build script
function build() {
    cd "${WORKDIR}/${NAME}-${VERSION}/build"

    make -j8
    make headers

    return 0
}

# Post build script
function postbuild() 
{
    cd "${WORKDIR}/${NAME}-${VERSION}/build"

    find usr/include -type f ! -name '*.h' -delete
    cp -rv usr/include $LFS/usr
    make -j8 modules_install
    cp -iv arch/x86/boot/bzImage /boot/vmlinuz-5.15-rc7-JaguarLinux-x86_64-dist
    cp -iv System.map /boot/System.map-5.15-rc7-JaguarLinux-x86_64-dist
    cp -iv .config /boot/config-5.15-rc7-JaguarLinux-x86_64-dist
    cp -r Documentation -T /usr/share/doc/linux-5.15-rc7-JaguarLinux-x86_64-dist
    install -v -m755 -d /etc/modprobe.d
    
    return 0
}
   


printf ("DONE")